### PR TITLE
BeGUI, simplify build scrips

### PR DESCRIPTION
**Pull request by Begasus**
This will move all the files for BeGUI in ./BeGUI, also added a cleaning section for when the build is finished

### CODE REVIEW

**Comment by humdingerb** [comment]
Looks good. Though, why do you clean up after building?
In case your working on the code, you often repeatedly do small changes and recompile. It'll save time not having to rebuild everything from scratch.

**Comment by Begasus** [comment]
Granted :) but in the original version this was done also by removing the build libraries and binaries, I could narrow it down to also just remove them instead of cleaning the objects directory

**Comment by Begasus** [comment]
> Looks good. Though, why do you clean up after building?
> In case your working on the code, you often repeatedly do small changes and recompile. It'll save time not having to rebuild everything from scratch.

On the other hand, if you keep the "build" objects, sometimes they are not rebuild after a second try (correct me if I'm wrong), so starting a clean build would be OK (since this is a small(er) project it doesn't take that much time to build anyway) ... thoughts on this welcome :)

**Comment by humdingerb** [comment]
That's why makefiles normally have a "clean" target. You could add such a parameter to this script, too. We may also leave all that to any dev that may one day pick up this project...

**Comment by Begasus** [comment]
@humdingerb created a separate script to clean the build, couldn't find a clean solution for now :) if need be I'll remove the cleaning script and just update the buildscript

**Review by humdingerb — COMMENTED** [review]
Looks, good!
Maybe add an `echo Done!` at the end of the cleaning script.
Also, the ReadMe has to be adjusted wrt the renamed build script. Maybe add a short hint to the clean script as well.

**Comment by Begasus** [comment]
Forgot about this one (shame) :)
Will try to give it another look shortly

**Comment by Begasus** [comment]
@humdingerb made some changes, could you check?

**Comment by humdingerb** [comment]
LGTM. Merge. :)
Thanks!

**Comment by Begasus** [comment]
Was looking into a build for x86_64, got a full build in the end, but running the app gave `Could not resolve symbol '_klock_node_' `:)

**Pull request merged**
