### PR TITLE
Update of makefiles and scripts and replaced .r with .rdef

### PR DESCRIPTION
**Pull request by abt2804**
- Updated makefiles.
- Replaced all .r with .rdef
- New Makefiles
- Changed the source code in order to work on Haiku
- New script file 
- Changed the header files in PrefsEDgar and ResEDgar so that no problems will occur in future.

### CODE REVIEW

**Comment by scottmc** [comment]
Wow.  You got them converted, nice work.  Does it fully build yet without issues now?  Can you add a screenshot of it?

**Comment by abt2804** [comment]
@scottmc Yes, it does build successfully

**Comment by humdingerb** [comment]
Question is, why did you touch over a hundred header files?

**Comment by scottmc** [comment]
Looks like it was due to the first line in each header file.  Seems this program used to use the old metrowerks compiler and perhaps it liked having that line at the top of each header file?

**Comment by humdingerb** [comment]
Oh, sorry, I think I looked at a different file in another folder when I did a quick check...
Move along, nothing to see...

**Pull request merged**
